// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcelqcpluhbwmdqkxvhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZWxxY3BsdWhid21kcWt4dmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxMjY4NTYsImV4cCI6MjA5MzcwMjg1Nn0.vWUoezbUqEplEJEDW7z_1Vn0HGonK590WH7o0wIQfFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});